# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gotohRCPP <- function(sequencePattern, sequenceSubject, matrix, gapOpening, gapExtension, gapEnding, farIndels) {
    .Call('Gotoh_gotohRCPP', PACKAGE = 'Gotoh', sequencePattern, sequenceSubject, matrix, gapOpening, gapExtension, gapEnding, farIndels)
}

