library(amplican)
library(testthat)
context("amplican main making analysis of example files")

#devtools::load_all() # changes paths so that system.file points to the actual development folder

config <- system.file("extdata", "config.csv", package = "amplican")
fastq_folder <- system.file("extdata", package = "amplican")
results_folder <- system.file("extdata", "results", package = "amplican")

test_that("amplican runs through example files without any issues", {
  expect_message(amplicanPipeline(config, fastq_folder, results_folder, knit_files = FALSE))
})

# # after successfull amplican pipeline run, replace autogenerated
# # system links in .Rmd reports with system.file type of links
# # also make vignettes out of .Rmd reports
#
# # run this when developing and willing to generate new vignettes
# # for visual quality test and for the users to see example reports
# rmd_path <- file.path(results_folder, "reports")
# vignettes_path <- system.file('vignettes', package = 'amplican')
# runParam <- readLines(file.path(results_folder, "RunParameters.txt"))
# runParam <- gsub(config,
#                  "folder/leading/to/config/file/that/has/been/used.csv",
#                  runParam)
#
# cat(runParam, file = file.path(results_folder, "RunParameters.txt"), sep = "\n")
# for (rmd in list.files(rmd_path)) {
#   rmd_content <- readLines(file.path(rmd_path, rmd))
#   fixed_rmd_content <- gsub(paste0("'", system.file('extdata', 'results', package = 'amplican'), "'"),
#                             "system.file('extdata', 'results', package = 'amplican')",
#                             rmd_content)
#   cat(fixed_rmd_content, file = file.path(rmd_path, rmd), sep = "\n")
#
#   fixed_rmd_content <- c(fixed_rmd_content[1:10],
#                          "vignette: >",
#                          paste0("  %\\VignetteIndexEntry{example ",
#                                 sub("report_", "", tools::file_path_sans_ext(rmd)),
#                                 " report}"),
#                          "  %\\VignetteEngine{knitr::rmarkdown}",
#                          "  %\\VignetteEncoding{UTF-8}",
#                          fixed_rmd_content[11:length(fixed_rmd_content)])
#   cat(fixed_rmd_content, file = file.path(vignettes_path, paste0("example_", rmd)), sep = "\n")
# }
#
# devtools::build_vignettes()
