// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP amplican_gotohRCPP(SEXP sequencePatternSEXP, SEXP sequenceSubjectSEXP, SEXP matrixSEXP, SEXP gapOpeningSEXP, SEXP gapExtensionSEXP, SEXP gapEndingSEXP, SEXP farIndelsSEXP);

R_CallMethodDef callMethods[]  = {
  {"amplican_gotohRCPP", (DL_FUNC) &amplican_gotohRCPP, 7},
  {NULL, NULL, 0}
};

void R_init_amplican(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

