// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gotohRCPP
std::string gotohRCPP(std::string sequencePattern, std::string sequenceSubject, std::string matrix, int gapOpening, int gapExtension, bool gapEnding, bool farIndels);
RcppExport SEXP amplican_gotohRCPP(SEXP sequencePatternSEXP, SEXP sequenceSubjectSEXP, SEXP matrixSEXP, SEXP gapOpeningSEXP, SEXP gapExtensionSEXP, SEXP gapEndingSEXP, SEXP farIndelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type sequencePattern(sequencePatternSEXP);
    Rcpp::traits::input_parameter< std::string >::type sequenceSubject(sequenceSubjectSEXP);
    Rcpp::traits::input_parameter< std::string >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< int >::type gapOpening(gapOpeningSEXP);
    Rcpp::traits::input_parameter< int >::type gapExtension(gapExtensionSEXP);
    Rcpp::traits::input_parameter< bool >::type gapEnding(gapEndingSEXP);
    Rcpp::traits::input_parameter< bool >::type farIndels(farIndelsSEXP);
    __result = Rcpp::wrap(gotohRCPP(sequencePattern, sequenceSubject, matrix, gapOpening, gapExtension, gapEnding, farIndels));
    return __result;
END_RCPP
}
