// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gotohRCPP
std::string gotohRCPP(std::string sequencePattern, std::string sequenceSubject, std::string matrix, int gapOpening, int gapExtension, bool gapEnding, bool farIndels);
RcppExport SEXP amplican_gotohRCPP(SEXP sequencePatternSEXP, SEXP sequenceSubjectSEXP, SEXP matrixSEXP, SEXP gapOpeningSEXP, SEXP gapExtensionSEXP, SEXP gapEndingSEXP, SEXP farIndelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type sequencePattern(sequencePatternSEXP);
    Rcpp::traits::input_parameter< std::string >::type sequenceSubject(sequenceSubjectSEXP);
    Rcpp::traits::input_parameter< std::string >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< int >::type gapOpening(gapOpeningSEXP);
    Rcpp::traits::input_parameter< int >::type gapExtension(gapExtensionSEXP);
    Rcpp::traits::input_parameter< bool >::type gapEnding(gapEndingSEXP);
    Rcpp::traits::input_parameter< bool >::type farIndels(farIndelsSEXP);
    rcpp_result_gen = Rcpp::wrap(gotohRCPP(sequencePattern, sequenceSubject, matrix, gapOpening, gapExtension, gapEnding, farIndels));
    return rcpp_result_gen;
END_RCPP
}
