# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bezierPath <- function(x, y, detail) {
    .Call('_amplican_bezierPath', PACKAGE = 'amplican', x, y, detail)
}

getBeziers <- function(x, y, id, detail) {
    .Call('_amplican_getBeziers', PACKAGE = 'amplican', x, y, id, detail)
}

